# This is a basic workflow to help you get started with Actions

name: Deploy Maceys to Netlify

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
    paths:
      - 'sites/maceys/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ hashFiles('package-lock.json') }}

      - uses: actions/setup-node@v1
        with:
          node-version: '15'

      - run: npm ci

      - working-directory: sites/maceys
        run: npm run generate

      - uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: 'sites/maceys/dist'
          production-deploy: ${{ github.ref == 'refs/heads/master' }}
          alias: 'staging'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: '53d9ac35-d437-4bf5-9390-5871c153d563'
