name: Deploy Petersons to Netlify
env:
  FORCED: false
on:
  push:
    branches: [master]
    paths:
      - 'sites/petersons/**'
      - 'content/petersons/**'
      - 'content/_shared/**'
  workflow_dispatch:
    FORCED: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            .cache/nuxt/petersons
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - uses: actions/setup-node@v1
        with:
          node-version: '15'

      - run: npm ci

      - working-directory: sites/petersons
        run: GITHUB_REF=$GITHUB_REF CI=1 npm run generate --force-build=$FORCED --fail-on-error=true

      - uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: 'sites/petersons/dist'
          production-deploy: ${{ github.ref == 'refs/heads/master' }}
          alias: 'staging'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: '5cc33f06-b61f-4857-b81c-b4ba014af6cf'
