name: Deploy Media to Netlify
on:
  push:
    branches: [master]
    paths:
      - 'sites/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: 'sites/media/test'
          production-deploy: ${{ github.ref == 'refs/heads/master' }}
          alias: 'staging'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: '5b6b3023-23e6-4746-8c97-6a8a6995cbfe'
