name: Deploy Media to Netlify
on:
  push:
    branches: [master]
    paths: |
      **/static/**/*.png
      **/static/**/*.jpg
      **/static/**/*.pdf
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: netlify/actions/build@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB }}
          NETLIFY_SITE_ID: 773a841f-8447-44b1-8ed7-3c97832501f4
          NETLIFY_CMD: npm run deploy-media
          NETLIFY_DIR: dist/media
